---
title: "cross validation"
author: "Janelle Layton"
date: '2022-07-13'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load packages
```{r}
library(tidyverse)
library(vista) 
library(mgcv)
```

# Load Data

```{r}
rmarkdown::render(here::here('scripts','sdmTMB data construction.Rmd'),quiet=TRUE)
```

# sdmTMB Model Function

```{r}
prepare_species <- function(dat,spp){
  dat_sub <- dat %>% 
    filter(species==spp) %>% 
    
    # rescale depth, oxygen, and temp to be N(0,1)
    mutate(across(c(depth_trawl,mean_temp_roms_30,mean_oxygen_roms_30),~(scale(.) %>% as.vector()),.names="{.col}_norm")) %>% 
    
    # add a year indicator
    mutate(year=lubridate::year(date))
}
```

```{r}
run_sdmTMB_cv <- function(dat,spp,nknots=400,use_depth=T,time_vary=F,spatial_field=T,include_substrate=T,hab_spline=F,env_spline=F,spline_k=3,return_what='loglik'){
  # filter data for species
  modeldat <- prepare_species(dat,spp=spp)
  
  # make spde
  spde <- make_mesh(modeldat,xy_cols = c('longitude','latitude'), 
                   cutoff = 20)
  
  # model formula
  formula <- paste0("cpue_kg_km2 ~ ")
  
  # substrate relationship
  substrate <- paste("prop_hard_mixed + I(prop_hard_mixed^2)")
  #wiggly habitat relationship?
  substrate <- ifelse(hab_spline, paste0("s(prop_hard_mixed,k=",spline_k,")"),
                      substrate)
  if(!include_substrate) substrate=""
  
  # make the environmental effects
  enviro <- paste("mean_temp_roms_30_norm + I(mean_temp_roms_30_norm^2) + mean_oxygen_roms_30_norm + I(mean_oxygen_roms_30_norm^2)")
  # wiggly environmental relationships?
  enviro <- ifelse(env_spline, paste0("s(mean_temp_roms_30_norm,k=",spline_k,") + ",
                                      "s(mean_oxygen_roms_30_norm,k=",spline_k,")"),
                   enviro)
  # if depth effect, add to model formla
  if(use_depth) {
    formula = paste0(formula, " + depth_trawl_norm + I(depth_trawl_norm^2)")
  }
  
  time_formula = "~ -1"
  if(time_vary) {
    time_formula = paste0(time_formula, " + ", substrate, " + ", enviro)
    time_varying = as.formula(time_formula)
    time = "year"
  } else {
    formula = paste0(formula, substrate, " + ", enviro)
    time_varying = NULL
    time = "year"
  }
  
  # fit model. EW commented out quadratic roots, since those are still experimental and won't work for all spp. Also turned
  set.seed(41389) # for reproducibility
  test_set = sample(1:nrow(modeldat), size = round(0.1*nrow(modeldat)), replace=FALSE)
  modeldat$fold = 1
  modeldat$fold[test_set] = 2 
  
  print('running 2-fold CV.')
  
  m_cv <- try( sdmTMB_cv( 
    formula = as.formula(formula),
    k_folds=2,
    parallel = TRUE,
    fold_ids = modeldat$fold,
    time_varying = time_varying,
    mesh = spde,
    time = time,
    family = tweedie(link = "log"),
    data = modeldat,
    anisotropy = FALSE,
    spatial = spatial_field
    #extra_time argument necessary for prediction?
    # extra_time=1980:2100,
    # control=sdmTMBcontrol(map_rf=ifelse(spatial_field,F,T))
  ),
  silent=T)
  if(class(m_cv)=='try-error'){
    print(paste('Error.'))
  } else{
    # tem <- m_cv %>% pluck('data')
    # print(paste('data is class',class(tem)))
    total_pred_ll = m_cv %>% 
      pluck('data') %>% 
      dplyr::filter(cv_fold==2) %>% 
      pluck('cv_loglik') %>% 
      sum()
    if(return_what=='model') return(m_cv)
    else return(total_pred_ll)
  }
}
```

## Choose a species

```{r}
spp <- "longnose skate"

spp_dat <- prepare_species(trawl_roms_utm,spp)

```

# Model output

```{r}
m <- run_sdmTMB_cv(dat=trawl_roms_utm,spp="longnose skate",use_depth=T,env_spline=T,include_substrate=T)
summary(m)
```